replicaCount: 3

image:
  repository: daniyaalabbas/calculator-app
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

config:
  APP_TITLE: "AI - Calculator v4🚀"
  ENVIRONMENT: "Development"

secret:
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: password123

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5
