apiVersion: apps/v1
kind: Deployment

metadata:
  name: calculator-app

spec:
  replicas: 6

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: calculator

  template:
    metadata:
      labels:
        app: calculator

    spec:
      containers:
      - name: calculator
        image: daniyaalabbas/calculator-app:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"

        env:
        - name: APP_TITLE
          valueFrom:
            configMapKeyRef:
              name: calculator-config
              key: APP_TITLE

        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: calculator-config
              key: ENVIRONMENT

        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: calculator-secret
              key: ADMIN_USERNAME

        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: calculator-secret
              key: ADMIN_PASSWORD

        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
